Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'snippets/**/*'

Style/EmptyMethod:
  Exclude:
    - 'lib/**/*'

AllCops:
  TargetRubyVersion:
    2.5
  Exclude:
    - 'spec/spec_helper.rb'
