Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'snippets/**/*'

Style/EmptyMethod:
  Exclude:
    - 'lib/**/*'
Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion:
    2.5
  Exclude:
    - 'spec/spec_helper.rb'
